### ISSUE TITLE
Ready Your Shovels

### ISSUE THREAD

**Issue by Rotzo** [CyanideX/Unity-Modded#11]
[https://www.curseforge.com/minecraft/mc-mods/ready-your-shovels](https://www.curseforge.com/minecraft/mc-mods/ready-your-shovels)

**Comment by CyanideX** [comment]
The developer doesn't seem to be very active and the mod is still in a beta for 1.14. 😕
I do like the look of the mod though. If it ever gets an update for 1.15/1.16, we can reopen this.
