### ISSUE TITLE
1.16.1 IamMusicPlayer

### ISSUE THREAD

**Issue by Ibirtem** [CyanideX/Unity-Modded#33]
https://www.curseforge.com/minecraft/mc-mods/iammusicplayer 
Buttons and models is to boring and not vanilla look... I will be very glad to see your textures~

**Comment by CyanideX** [comment]
![img](https://media1.giphy.com/media/10FHR5A4cXqVrO/200w.gif)

**Comment by CyanideX** [comment]
Sorry, this is not a mod I plan to add support for.
