### ISSUE TITLE
[1.16.1] Storage Drawers

### ISSUE THREAD

**Issue by Leorgito** [CyanideX/Unity-Modded#36]
**Mod**
Storage Drawers

**Download**
https://www.curseforge.com/minecraft/mc-mods/storage-drawers

**Comment by CyanideX** [comment]
Why did you close this? We have it on our todo list.

**Comment by Leorgito** [comment]
> Why did you close this? We have it on our todo list.

Sorry, my bad. I'm going to reopen the suggestion! :)
