### ISSUE TITLE
.

### ISSUE THREAD

**Issue by vemifol** [CyanideX/Unity-Modded#43]

**Comment by CyanideX** [comment]
Really? This again? 😒 

#40  #41 #44

**Comment by CyanideX** [comment]
![image](https://user-images.githubusercontent.com/3106700/94637091-892bf080-028b-11eb-976e-5bf406beeac1.png)
![artist](https://user-images.githubusercontent.com/3106700/94638325-8f6f9c00-028e-11eb-8ef2-77d3a273eb74.gif)
