### ISSUE TITLE
[1.2.0] Iron Chests: Textures mixed up

### ISSUE THREAD

**Issue by brisingraerowing** [CyanideX/Unity-Modded#50]
**Describe the Issue**
The inside textures of any iron chests chest are on the outside, and vice versa.

**To Reproduce**
1. Install Unity Modded and Iron Chests
2. Place any iron chests chest
3. Observe

**Expected Behavior**
Inside textures are, well, inside.

**Screenshots**
![2021-01-03_17 26 46](https://user-images.githubusercontent.com/250409/103490344-35302b00-4de9-11eb-9ed7-232011a6d3da.png)

![2021-01-03_17 26 49](https://user-images.githubusercontent.com/250409/103490345-382b1b80-4de9-11eb-9ed7-e3b3121a0470.png)

**Additional Context**
No Optifine (breaks too many things).

**Comment by CyanideX** [comment]
I'm assuming this is 1.16+?

**Comment by brisingraerowing** [comment]
Yup.

**Comment by CyanideX** [comment]
Fixed in 76c3fdc 🙂
