### ISSUE TITLE
1.16.4-5 CannabisCraft

### ISSUE THREAD

**Issue by SugarBunnyKiss** [CyanideX/Unity-Modded#56]
CannabisCraft

https://www.curseforge.com/minecraft/mc-mods/cannabiscraft

The UV light, Medicated food items, & Cannavision/Vignette effects could use your expertise the most but it wouldn't hurt to further update the rest of the items to be more crisp & vibrant!

textures : 
1 UV light, 3 plant varieties w/ a potted & farmland variant, 4 bud variants, 4 joint variants, 4 vignette effects, 4 grinders, 1 drying rack, 6 or 8 vanilla foods that are medicated w/ the 3 plants each

**Comment by CyanideX** [comment]
I don't want to make a habit of retexturing meme mods and would prefer to focus on more popular mods with substantial content.

**Comment by SugarBunnyKiss** [comment]
Fair enough lol, 🤞🤞 here's hoping more people tak up this mod!!

**Comment by BBoldt** [comment]
420 blaze it
