### ISSUE TITLE
Nether racks blocks issues? 

### ISSUE THREAD

**Issue by Zu-Sushi** [CyanideX/Unity-Modded#61]
I noticed some gold ores and quartz ores in nether are too light compare to nether rack blocks are too dark. There's sometime buggy to see pitch black nether rack blocks. I'm using Valhelsia 3 modpack which included Biomes o Plenty.

**Comment by CyanideX** [comment]
Please follow the issue template; I've put it in place for a reason (hint: it's to help me track down the issue).

> **Describe the Issue**
> A clear and concise description of what the issue is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected Behavior**
> A clear and concise description of what you expected to happen.
> 
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
> 
> **Additional Context**
> Add any other context about the problem here. What mod is causing the issue? What other resource packs do you have enabled? Are you using OptiFine?


I need screenshots, resource packs, etc.

Are you you're using Unity: Extras?

**Comment by Zu-Sushi** [comment]
**Describe the Issue**
Darker color Nether racks than usually. mismatching texture to gold ores/quartz/other biomes [Crimson and Warped| 

**To Reproduce**
Just go into nether, happened to find them in these condition. 

**Expected Behavior**
Same texture color match others?

**Screenshots**
https://gyazo.com/444f2c76e20d911b914b8d51387e3614

https://gyazo.com/801521579b83ee2e346859699c9d3d33

**Additional Context**
Valhelsia 3 with some additional mods. This is 1.16.5
I am using optifine for shader but i disabled shader.
I am using Unity, Unity Dark, Unity Extra, and Modded.

**Comment by Zu-Sushi** [comment]
Oh, Unity Extra is the issue to make netherrack blocks darker/black because I don't have CTM for 1.16.5. Only i see 1.16.4? does it work for it?

Edits:

Look like Valhelsia 3 has CTM already but why it is not working?

**Comment by CyanideX** [comment]
The issue is with the netherrack block colormap found in **_assets\minecraft\optifine\colormap\custom_**. It is a work in progress at the moment but you can safely delete the custom folder to fix the issue.

**Comment by Zu-Sushi** [comment]
and where i can find this specific folder?

**Comment by CyanideX** [comment]
**.minecraft\resourcepacks\Unity Extras _(if it's a zip, open with 7Zip or WinRar or something)_ \assets\minecraft\optifine\colormap\custom**

**Comment by Zu-Sushi** [comment]
that work even better, thank you!
