### ISSUE TITLE
[1.12.2] RLCraft (Lycanites Mobs, Ice and Fire, Wearable Backpacks ...)

### ISSUE THREAD

**Issue by strayhatpirat** [CyanideX/Unity-Modded#77]
**Mod(pack)**
_RLCraft modpack ; mainly mods such as :_
_- Lycanites Mobs,_ 
_- Ice and Fire,_ 
_- Wearable Backpacks,_ 
_- Antique Atlas,_ 
_- Tough as Nails,_ 
_- No Tree Punching,_ 
_- Defiled Lands,_ 
_- Familiar Fauna,_ 
_- Serene Seasons ..._

**Download**
_https://www.curseforge.com/minecraft/modpacks/rlcraft_
_https://www.curseforge.com/minecraft/modpacks/rlcraft/relations/dependencies_

**Optional: Asset Details**
_It's a huge work to do but it would be awesome._

**Comment by ChloeDawn** [comment]
Individual mods should be requested as individual tickets for simpler project management. If you do not want to spend the time doing that, we do not want to spend the time retexturing *an entire modpack*.
