### ISSUE TITLE
[1.18] Mekanism

### ISSUE THREAD

**Issue by PanAntooni** [CyanideX/Unity-Modded#84]
**Mod**
_Enter the name of the mod here. (Example: Mekanism)_

**Download**
_Provide a download link to the suggested mod._

**Optional: Asset Details**
_If possible, mention how many assets/textures will need to be retextured._

**Comment by ChloeDawn** [comment]
Firstly, you didn't fill out the template correctly, and secondly, Mekanism is already using Unity-style textures.![Screenshot of the Mekanism project member list featuring CyanideX as the artist](https://user-images.githubusercontent.com/9869940/181912075-8f186718-ea65-4302-8431-e0736da8bc29.jpg)
