### ISSUE TITLE
[1.19.2] IC2 Classic

### ISSUE THREAD

**Issue by XXxinsanityxX** [CyanideX/Unity-Modded#89]
IC2 Classic

https://www.curseforge.com/minecraft/mc-mods/ic2-classic

Besides new additions to the mod, i believe most of the stuff was already textured by unity at some point.

**Comment by CyanideX** [comment]
Asset replacement doesn't seem to work at the moment.

The mod doesn't currently offer support for blockstate or model changes.

Please feel free to reopen when the mod is in a more stable and resource pack-friendly state.

**Comment by Speiger** [comment]
@CyanideX very unlikely to happen, since i am not using Unity-Modded.
